//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Depozit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public int Id { get; set; }
        public System.DateTime Date_of_Credit { get; set; }
        public decimal Price { get; set; }
        public int People_Id { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
