//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Depozit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DepozitDbEntities2 : DbContext
    {
        public DepozitDbEntities2()
            : base("name=DepozitDbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Credit> Credits { get; set; }
        public virtual DbSet<Person> People { get; set; }
    
        public virtual ObjectResult<usp_People_Result> usp_People()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_People_Result>("usp_People");
        }
    }
}
